_wandb:
    value:
        cli_version: 0.22.3
        e:
            szw17g7d03lxgm6gn5gxxra4vjc210s5:
                codePath: DQN_Breakout\utils.py
                codePathLocal: utils.py
                cpu_count: 12
                cpu_count_logical: 24
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "275012120576"
                        used: "1375969280"
                email: 3210102964@zju.edu.cn
                executable: D:\miniconda3\envs\rl\python.exe
                git:
                    commit: a2a5023d8d19e6fa3491d78e7aeae940a0c662fd
                    remote: https://github.com/XiaLiangming/RL.git
                gpu: NVIDIA GeForce RTX 5070 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 8960
                      memoryTotal: "17094934528"
                      name: NVIDIA GeForce RTX 5070 Ti
                      uuid: GPU-8704bed2-4e3d-ec48-8b5f-04d56acf8b39
                host: CarpeDiem
                memory:
                    total: "33407602688"
                os: Windows-10-10.0.26100-SP0
                program: F:\ExperiCode\RL\DQN_Breakout\utils.py
                python: CPython 3.9.23
                root: F:\ExperiCode\RL\DQN_Breakout
                startedAt: "2025-10-31T03:26:00.679623Z"
                writerId: szw17g7d03lxgm6gn5gxxra4vjc210s5
        m: []
        python_version: 3.9.23
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
            "4": 3.9.23
            "5": 0.22.3
            "8":
                - 3
            "12": 0.22.3
            "13": windows-amd64
